spring:
  profiles:
    active: local
    include: my, private
  jpa:
    hibernate:
#       ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.springframework.web: TRACE